pipeline {
  agent any
  SERVICE = 'scoring-service'
  stages{
    stage('Git') {
     steps{
         checkout scm
         }
     }

    stage('Setup') {
      steps{
        sh '''
          cd ${SERVICE}
          npm install
          '''
      }
    }
    stage('Test') {
      steps{
          sh '''
            cd ${SERVICE}
            ./node_modules/mocha/bin/mocha test/**
            '''
      }
    }
    stage('Docker') {
      steps{
          sh '''
          cd ${SERVICE}
          #docker build -f Dockerfile -t 10.94.1.14:5000/${SERVICE}:${BUILD_NUMBER}-SNAPSHOT .
          #docker push 10.94.1.14:5000/${SERVICE}:${BUILD_NUMBER}-SNAPSHOT
          docker build -f Dockerfile -t 10.94.1.14:5000/${SERVICE}:${GIT_COMMIT} .
          docker push 10.94.1.14:5000/${SERVICE}:${GIT_COMMIT}
          '''
      }
    }
  }
}
