pipeline {
  agent any
  stages{
    stage('Setup') {
      steps{
        sh '''
          cd loan-service
          npm install
          '''
      }
    }
    stage('Test') {
      steps{
          sh '''
            cd loan-service
            ./node_modules/mocha/bin/mocha test/**
            '''
      }
    }
    stage('Docker') {
      steps{
          sh '''
          cd loan-service
          docker build -f Dockerfile -t loan-service .
          '''
      }
    }

  }
}
