pipeline {
  agent any
  stages{
    stage('Setup') {
      steps{
        sh '''
          cd loan-service
          npm install
          '''
      }
    }
    stage('Test') {
      steps{
        script{
          sh '''
            cd loan-service
            ./node_modules/mocha/bin/mocha test/**
            '''
        }
      }
    }
  }
}
