pipeline {
  agent any
  stages{
    stage('Setup') {
      steps{
        sh '''
          cd loan-service
          npm install
          '''
      }
    }
    stage('Test') {
      steps{
          sh '''
            cd loan-service
            ./node_modules/mocha/bin/mocha test/**
            '''
      }
    }
    stage('Docker') {
      steps{
          sh '''
          cd loan-service
          docker build -f Dockerfile -t 10.94.1.14:5000/loan-service:${BUILD_NUMBER}-SNAPSHOT .
          docker push 10.94.1.14:5000/loan-service:${BUILD_NUMBER}-SNAPSHOT
          '''
      }
    }

  }
}
